[build]
  command = "npm install && npm run build"
  publish = "web-build"

[context.production]
  command = "npm install && npm run web:build"

[context.develop]
  command = "npm install && npm run web:build"

[context.branch-deploy]
  command = "npm install && npm run web:build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps --force"
  CI = "false" 